compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  # Core configs
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 32
  zero_stage: 2

  # Memory optimizations
  zero_optimization:
    stage: 2
    allgather_partitions: true
    reduce_scatter: true
    overlap_comm: true
    contiguous_gradients: true
    cpu_offload: true
  
  # Optimizer settings
  offload_optimizer:
    device: cpu
    pin_memory: true
    buffer_count: 4
    fast_init: true
  
  # Gradient clipping
  gradient_clipping: 1.0
  
  # Communication optimizations  
  communication_data_type: "bf16"
  round_robin_gradients: true
  
  # Performance optimizations
  steps_per_print: 100
  wall_clock_breakdown: false
  fp16:
    enabled: true
    loss_scale: 0
    initial_scale_power: 16
    loss_scale_window: 1000
    hysteresis: 2
    min_loss_scale: 1

distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 3
rdzv_backend: static
same_network: true
use_cpu: false
