output_global_parent_dir: results
wandb_run_id: rloo_llama3-8b_countdown 
output_dir: rloo_llama3-8b_countdown
run_name: rloo_llama3-8b_countdown
dataset_name: countdown234
dataset_test_split: validation
max_length: 2048
bf16: True
## ppo stuff
total_episodes: 100000
response_length: 2000
num_ppo_epochs: 1
num_mini_batches: 1 
learning_rate: 5.0e-7
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
model_name_or_path: mnoukhov/pythia410m-sft-tldr
sft_model_path: mnoukhov/pythia410m-sft-tldr
reward_model_path: mnoukhov/pythia410m-rm-tldr6.9b
local_rollout_forward_batch_size: 8
non_eos_penalty: False
stop_token: eos
save_strategy: steps
save_steps: 0.25
hub_strategy: none
logging_steps: 100
num_sample_generations: 5
rloo_k: 8
